# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "../output/vmware/rockylinux9-desktop.box"
  config.vm.define "rockylinux9-desktop"
  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
    v.vmx["numvcpus"] = "2"
    v.vmx["svga.graphicsMemoryKB"] = "8388608"
    v.vmx["memsize"] = "2048"
    v.vmx["mks.enable3d"] = true
  end
end
